<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Invio di Modulo contatti',
	'heading' => 'Nuovo invio del modulo',
	'success_redirect' => 'messaggio-inviato.html',
	'resources' => array(
		'checkbox_checked' => 'Selezionato',
		'checkbox_unchecked' => 'Non selezionato',
		'submitted_from' => 'Modulo inviato dal sito Web: %s',
		'submitted_by' => 'Indirizzo IP del visitatore: %s',
		'too_many_submissions' => 'Troppi invii recenti da questo IP',
		'failed_to_send_email' => 'Invio e-mail non riuscito',
		'invalid_reCAPTCHA_private_key' => 'Chiave privata reCAPTCHA non valida.',
		'invalid_reCAPTCHA2_private_key' => 'Chiave privata reCAPTCHA 2.0 non valida.',
		'invalid_reCAPTCHA2_server_response' => 'Risposta server reCAPTCHA 2.0 non valida.',
		'invalid_field_type' => 'Tipo di campo \"%s\" sconosciuto.',
		'invalid_form_config' => 'Il campo \"%s\" ha una configurazione non valida.',
		'unknown_method' => 'Metodo di richiesta server sconosciuto'
	),
	'email' => array(
		'from' => 'francesca.comicdesign@gmail.com',
		'to' => 'francesca.comicdesign@gmail.com'
	),
	'fields' => array(
		'custom_U81945' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'Nome\' è obbligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'E-mail\' è obbligatorio.',
				'format' => 'L\'e-mail del campo \"E-mail\" non è valido.'
			)
		),
		'custom_U81935' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Procedendo accetti la privacy policy',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'Procedendo accetti la privacy policy\' è obbligatorio.'
			)
		),
		'custom_U82021' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Messaggio',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'Messaggio\' è obbligatorio.'
			)
		),
		'custom_U82033' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Oggetto',
			'required' => true,
			'errors' => array(
				'required' => 'Il campo \'Oggetto\' è obbligatorio.'
			)
		)
	)
);

process_form($form);
?>
